version: "2"
checks:
  argument-count:
    config:
      threshold: 4
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-7"
exclude_patterns:
  - "node_modules/"
  - "spec/"
