version: "2"
checks:
  argument-count:
    config:
      threshold: 4
plugins:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
exclude_patterns:
  - "node_modules/"
  - "test/"
